### ISSUE TITLE
Create a personal wiki page

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#1]
# About
I'll create a personal wiki page, as everyone should do.

## TODO
- [x] Create a personal wiki page.
- [x] Add its link to the home wiki page.
- [x] Add its link to the `Group Members` sidebar.
