### ISSUE TITLE
Contribute to API research

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#12]
# About

Since everyone has researched a new API in our team (some other groups did it differently - they researched a single API as a team), I'll do my research separately too.

## TODO

- [x] Choose an API to research.
- [x] Select most important categories to include in the research.
- [x] Make the research.
- [x] Open the Wiki page.
- [x] Add its links to the other wiki pages.

**Comment by smddzcy** [comment]
My research is about Docker Remote API. You can see it here: https://github.com/bounswe/bounswe2017group3/wiki/Docker-Remote-API
