### ISSUE TITLE
Improve the communication plan page according to the feedback

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#19]
# About

Özlem (our customer) has given us some [feedback](https://piazza.com/class/iy2vi1es6ta4jc?cid=47) on the communication plan page. We should improve the page according to her feedback.

## TODO

- [x] Move _customer_ definition to the glossary.
- [x] Remove _communicator_ definition since it's not related.
- [x] Add team members to the glossary.
