### ISSUE TITLE
Add some missing requirements

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#23]
# About
As a feedback from our customer (Özlem), we should add some missing requirements to our [requirements page](https://github.com/bounswe/bounswe2017group3/wiki/Requirements).

## TODO
- [x] Add an item stating that we'll make android and web applications to non-functional requirements.
- [x] Add requirements about annotations.
- [x] Add subsections about user types to user requirements.

**Comment by gokceuludogan** [comment]
I have added the requirements about annotations but it could be better if someone reviews it

**Comment by smddzcy** [comment]
@gokceuludogan Looks perfect 👌
