### ISSUE TITLE
Make the requirements more specific and clear

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#24]
# About

As a feedback from our customer (Özlem), some of our requirements are not clear and specific enough. We should make them specific and measurable.

## TODO
- [x] Improve the wording of _"interact"_ on **1.1.4.4** and make it more specific.
- [x] Improve the wording of _"items of interest"_ on **1.1.4.1** and make it more specific. Our customer says that: We should say in which forms it can be, and which formatted items can be created with which fields, is it fixed or variable, who decides all this etc.
- [x] Make the items on the non-functional requirements measurable. An example from our customer: On **2.1.1**, it should be something like _"The system shall use XXX for safety"_, not _"The system shall guarantee the safety"_.

**Comment by smddzcy** [comment]
I've made the minor changes such as fixing typos, settings header sizes and improving the consistency across the document by rewording some phrases. It looks good now, closing this issue 👍
