### ISSUE TITLE
Add mockups for privacy settings

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#35]
# About

Users should be able to set the privacy settings for **events**, **groups** and **their profile information**. There'll be 2 options: **public** or **private**. Guests won't be able to see the private things.

## Design

I think a Facebook-like dropdown is enough.
<img width="152" alt="screen shot 2017-03-06 at 11 28 42" src="https://cloud.githubusercontent.com/assets/13895224/23602152/b0046968-0257-11e7-92d0-465e44b57477.png">

## TODO
- [x] Add mockups for event privacy settings.
- [x] Add mockups for group privacy settings.
- [x] Add mockups for profile information privacy settings.

**Comment by gokceuludogan** [comment]
I have added mockup for group privacy settings and changed the moderator page and change template mockups accordingly. Here are the visuals of them: 

![moderator page](https://cloud.githubusercontent.com/assets/9639399/23605196/6c1677ca-0264-11e7-97bd-380d76512daa.png)

![change privacy](https://cloud.githubusercontent.com/assets/9639399/23605194/6c137f02-0264-11e7-80a7-15e6dab7a7c0.png)

![new change template](https://cloud.githubusercontent.com/assets/9639399/23605195/6c14367c-0264-11e7-8f8b-9ce0c5b49523.png)

**Comment by gokceuludogan** [comment]
I have also added mockups for event privacy and profile information settings. Additionally, I have changed the mockups related to these ones. Here are the new versions of these mockups:

![event page](https://cloud.githubusercontent.com/assets/9639399/23614014/3c5614fc-028a-11e7-80f7-1dcc44d47ae2.png)

![event page - change privacy](https://cloud.githubusercontent.com/assets/9639399/23614013/3c53418c-028a-11e7-9234-4eeb535d72bb.png)
![moderator page - pending group join requests](https://cloud.githubusercontent.com/assets/9639399/23614015/3c59aa40-028a-11e7-8ed0-ef4190eaf6da.png)

![moderator page - add users to group](https://cloud.githubusercontent.com/assets/9639399/23614016/3c5abe80-028a-11e7-87b3-36d843e9a644.png)

![moderator page 2](https://cloud.githubusercontent.com/assets/9639399/23614018/3c650fb6-028a-11e7-8b1f-2e65d0a6f4cf.png)

![my profile page - about](https://cloud.githubusercontent.com/assets/9639399/23614021/3c8a7f12-028a-11e7-878a-9805440cbabd.png)

![my profile page - about - edit](https://cloud.githubusercontent.com/assets/9639399/23614019/3c83d522-028a-11e7-92d8-32c12eac273b.png)
![my profile page - about - followers_ click](https://cloud.githubusercontent.com/assets/9639399/23614020/3c889d3c-028a-11e7-8859-d57b9e43784a.png)

![my profile page - change privacy](https://cloud.githubusercontent.com/assets/9639399/23614023/3c94d9bc-028a-11e7-90ea-52fae0f5fcc7.png)

**Comment by gokceuludogan** [comment]
My Profile Page - About - Edit with a little change 
![Uploading My Profile Page - About - Edit.png…]()

**Comment by gokceuludogan** [comment]
My Profile Page - About - Edit with a little change
![my profile page - about - edit](https://cloud.githubusercontent.com/assets/9639399/23614704/937dfcb6-028c-11e7-85f6-f32992edd769.png)

**Comment by gokceuludogan** [comment]
Since I have completed and added them to the wiki page, I am closing this issue
