### ISSUE TITLE
Update Project Plan

### ISSUE THREAD

**Issue by MertKalaylioglu** [bounswe/bounswe2017group3#55]
- [x] Group the tasks
- [x] Add resources to project plan
- [x] Assign resources to the tasks
- [x] Determine precedences
- [x] Adjust weekends as working days
- [x] Change the appearance of milestones

**Comment by smddzcy** [comment]
@MertKalaylioglu thank you  👍
