### ISSUE TITLE
Create issue & pull request specifications

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#64]
## About

We'll start opening pull requests and pushing some code to the repository soon, but before that, we should put these things into a structure.

We should create an issue specification page that defines **which label is used when**, **what are things in the right panel of issue creation page and how to use them** (_Assignees_, _Projects_), **what is the format of an issue** (although I've created templates for issues and pull requests, I didn't create a wiki page to explain them - I just added some inline texts and hoped you read them, which sometimes you didn't 😅).

We should also create a pull request specification page that defines **development**, **review** and **deployment** processes, as well as the **structure of a pull request**. The development part should include **branch naming policy**, **commit frequency**, **testing policy**, **documentation policy**, **pull & push policy**. The review part should include a **review policy**. The deployment part should include a **deployment policy**. In the structure of a pull request part; it can be similar to the issue specification with no major changes since they're quite similar.

## Visuals

Right panel of issue creation page. We'll (hopefully) try to use these as effective as possible.
<img width="449" alt="screen shot 2017-04-09 at 03 02 13" src="https://cloud.githubusercontent.com/assets/13895224/24833441/f1826f0a-1cd0-11e7-9b2f-71ab31e03464.png">

## To-do

- [x] Create the issue specification page.
  - [x] Write the label policy.
  - [x] Explain how _Assignees_ will be used.
  - [x] Explain how _Projects_ will be used.
    - [x] Explain the kanban board and how to use it.
- [x] Create the pull request specification page.
  - [x] Write the structure of a pull request.
  - [x] Write the development part.
    - [x] Write the branch naming policy.
    - [x] Write the commit frequency part.
    - [x] Write the testing policy.
    - [x] Write the documentation policy.
    - [x] Write the pull & push policy.
  - [x] Write the review part.
    - [x] Write the review policy.
  - [x] Write the deployment part.
    - [x] Write the deployment policy.

**Comment by smddzcy** [comment]
@bounswe/bounswe2017group3 Here's a good post that explains pull requests: https://medium.com/@mscccc/jr-developers-1-pull-requests-you-39a11c3bdd94

**Comment by smddzcy** [comment]
Issue specifications are ready: https://github.com/bounswe/bounswe2017group3/wiki/Creating-an-Issue

@bounswe/bounswe2017group3 Everyone **must** read and review this so that we can agree on it.

I'm going to write the pull request specifications and finish this tomorrow. 🤞

**Comment by smddzcy** [comment]
@bounswe/bounswe2017group3 Pull request specifications are ready too. Please read and review it 😄

**Comment by gokceuludogan** [comment]
They seem very nice and functional :clap:
