### ISSUE TITLE
Creating the requirements of our test application

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group3#68]
## About

We should create the requirements of our test application before creating its REST API. As all of you know, it'll be a _event listing application_ where users will be able to register and log into the system, create events, join events, or get all the events.

## To-do

- [x] Discuss the requirements of our test application.
- [x] Create the requirements of our test application.
- [x] Test the requirements of our test application.

**Comment by gokceuludogan** [comment]
I have created a page with our basic requirements [here](https://github.com/bounswe/bounswe2017group3/wiki/API-Requirements). Could you review it and add new ones if necessary, please? @smddzcy

**Comment by smddzcy** [comment]
I've made some of the requirements more concrete and clear, added the requirement about tokens, added a brief description, and fixed the formatting. Maybe we can add some more non-functional requirements later on, but it looks enough at the moment, you can close it after taking another look 👌 

**Edit:** Oh, also, we need to add this page's link to somewhere in the wiki 😅

**Comment by mtoygar** [comment]
I have added the link under project documentation in wiki, if we dont have any further addition to the requirements we can close this issue :muscle:
