### ISSUE TITLE
Divide API tasks among team 

### ISSUE THREAD

**Issue by esra-aydemir** [bounswe/bounswe2017group3#72]
## About

* **Related Issues:**
[Creating the requirements of our test application #68 ](https://github.com/bounswe/bounswe2017group3/issues/68) 
* **Other Related Links:** 
[Initial configuration for our events application and basic user endpoints #71](https://github.com/bounswe/bounswe2017group3/issues/71) 

We need to create an API and all members must contribute to it. To achieve this we first need to have enough number of requirements to share tasks between members. This means this issue can be only completed after [creating the requirements#68](https://github.com/bounswe/bounswe2017group3/issues/68) .
But we can go parallel to that process so I open this issue to decide who will implement the specified requirements. We can add and assign to members new tasks as they are added to requirements.
I am listing the existing requirements below. Since the tasks are similar you can assign any task you wish to yourself. But it is important for all members to be assigned to at least one task. 
Feel free to edit/comment this issue to improve task sharing. If the part you have done is not in the to do list please comment on what you have done or add it to the list.

## To-do

- [x] Create initial configuration of the api. @smddzcy 
- [ ] add related tasks to the list below when the requirements are updated/completed.
- [ ] assign one of the tasks to yourself and implement it. @bounswe/bounswe2017group3  

Existing requirements to be implemented:
- [x] create event @esra-aydemir
- [ ] retrieve all events @memhak 
- [ ] retrieve an event @memhak 
- [x] delete event @mtoygar
- [ ] update event @mehmetcalim
- [x] add privacy to event @MertKalaylioglu
- [x] retrieve events by privacy @MertKalaylioglu
- [x] retrieve all users
- [x] retrieve a user {
    - [x] get user by id @ugurcanarikan
    - [x] get user by username @gokceuludogan
    - [x] get user by fullname @onurorhan
}
- [x] add user
- [x] edit user @gokceuludogan
- [x] delete user @buraktomruk

**Comment by smddzcy** [comment]
Add a user and retrieve all users are already implemented 👍

**Comment by gokceuludogan** [comment]
I can handle the tasks which are retrieving user and editing user. However, we can add options to them such as: getting user by id, username, fullname etc. if there is not enough task for each member of team.

**Comment by esra-aydemir** [comment]
It seems reasonable. I will 
- [x] add those to the requirements and 
- [x] edit the list, 
then you can take which ones you want and implement those.
By the way you can assign yourself above to let anyone see easily who is doing which task.
And I will take the create event task. I can try others also if everyone takes a task and some other tasks remain.

**Comment by memhak** [comment]
I think I can handle retrieve all events and retrieve an event tasks. 👍

**Comment by ugurcanarikan** [comment]
I can take get user by id and delete an event

**Comment by OnurOrhan** [comment]
I am assigning myself the remaining "get user by full name"

**Comment by smddzcy** [comment]
To help you out with the routing:
Get X by id should be like this: `/X/:id`
Get X by anything other than id should use query params like this: `/X?param1&param2&...&paramN`

So, for `User` example:
- `/user/15` should return a single user with id 15.
- `/user?name=Samed` should return the users (an array) who have the name Samed.
- `/user?name=Samed&age=25` should return the users (an array) who have the name Samed and age 25.

**Comment by mehmetcalim** [comment]
I can take update event.

**Comment by mtoygar** [comment]
I take the delete event task from @ugurcanarikan.

**Comment by smddzcy** [comment]
By the way, I've just noticed that I forgot to add a getter for `id` to `User`. Someone should better implement a `long getId()` method on `User` class 😄

**Comment by gokceuludogan** [comment]
@smddzcy I have added `long getId()` method :+1:

**Comment by buraktomruk** [comment]
I take the "delete user".
