### ISSUE TITLE
Create test cases for our project

### ISSUE THREAD

**Issue by gokceuludogan** [bounswe/bounswe2017group3#85]
## About
* **Other Related Links:** https://github.com/bounswe/bounse2017group3/wiki/Use-Cases

We should create test cases for our project mostly based on our use cases. Please assign at least one of them to yourself and feel free to add new test cases that you think it is essential or remove if you think it is unnecessary. 

## To-do
- [x] Search an item. @gokceuludogan
- [x] Create a tag for item. @mtoygar
- [ ] Create an annotation. @memhak
- [x] Change privacy settings of a group/ an event. @MertKalaylioglu
- [x] Warn and ban a user. @smddzcy
- [x] Follow a group. @ugurcanarikan
- [x] Send invitation to a user. @buraktomruk
- [x] Create a group. @esra-aydemir
- [x] Create a post. @OnurOrhan
- [ ] Create an item. @mehmetcalim
- [ ] Recommend an item.

**Comment by gokceuludogan** [comment]
I have created an initial template which you can use while writing the test cases https://github.com/bounswe/bounswe2017group3/wiki/Test-Cases

**Comment by mtoygar** [comment]
I have added test cases for "create a tag for an item" to [wiki](https://github.com/bounswe/bounswe2017group3/wiki/Test-Cases). Can you guys review?

**Comment by gokceuludogan** [comment]
@mtoygar Test cases should be like a scenario not like a list. For example, at the first step, user clicks search button, the second one is user writes keyword and so on. [Here]( https://github.com/bounswe/bounswe2016group6/wiki/Test-Cases) are some example test cases from last year. Additionally, it might be a good idea to create an issue for that since tracking of each test case could be hard within an issue.

**Comment by smddzcy** [comment]
I took the _"Ban a user."_ test case 👍

**Comment by memhak** [comment]
I'm taking "creating annotation" case 👍

**Comment by mehmetcalim** [comment]
I took "create an item" case.

**Comment by smddzcy** [comment]
@bounswe/bounswe2017group3 This is way overdue, just letting you know 😄
